project:
  type: website

website:
  title: "ISSS608 Zanelle's enclosed space"
  navbar:
    right:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: About
    
    left:
    - text: "Hands-On Exercise"
      menu:
      - href: "Hands-On_Exercise/Hands-On_Exercise_01.html"
        text: "1. A Layered Grammer of Graphics: ggplot2 method"
      - href: "Hands-On_Exercise/Hands-On_Exercise_02.html"
        text: "2. Beyond ggplot2 Fundamentals"
      - href: "Hands-On_Exercise/Hands-On_Exercise_03a.html"
        text: "3a. Programming Interactive Data Visualisation with R"
      - href: "Hands-On_Exercise/Hands-On_Exercise_03b.html"
        text: "3b. Programming Animated Statistical Graphics with R"
        
    - text: "In-Class Exercise"
      menu:
      - href: https://public.tableau.com/views/In-Class_Ex01_17371865795720/Dashboard1?:language=en-GB&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
        text: "In-Class Exercise 1"
      - href: https://public.tableau.com/views/In-Class_Ex02_17377898450610/Dashboard1?:language=en-GB&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
        text: "In-Class Exercise 2"
    
    - text: "Take-Home Exercise"
      menu:
        - href: "Take-Home_Exercise/Take-Home_Exercise_1.html"
          text: "Take-Home Exercise 1"

format:
  html:
    theme:
      - journal
    css: styles.css
    toc: true

editor: visual

