project:
  type: website

website:
  title: "ISSS608 Zanelle's enclosed space"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: About
    - text: "Hands-On Exercise"
      menu:
      - href: "Hands-On_Exercise/Hands-On_Exercise_00.html"
        text: "Hands-On Exercise 00"
      - href: "Hands-On_Exercise/Hands-On_Exercise_01.html"
        text: "Hands-On Exercise 01"
      - href: "Hands-On_Exercise/Hands-On_Exercise_02.html"
        text: "Hands-On Exercise 02"
    


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

