project:
  type: website

website:
  title: "ISSS608 Zanelle's enclosed space"
  navbar:
    right:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: About
    
    left:
    - text: "Hands-On Exercise"
      menu:
      - href: "Hands-On_Exercise/Hands-On_Exercise_01.html"
        text: "1. A Layered Grammer of Graphics: ggplot2 method"
      - href: "Hands-On_Exercise/Hands-On_Exercise_02.html"
        text: "2. Beyond ggplot2 Fundamentals"
      - href: "Hands-On_Exercise/Hands-On_Exercise_03a.html"
        text: "3a. Programming Interactive Data Visualisation with R"
      - href: "Hands-On_Exercise/Hands-On_Exercise_03b.html"
        text: "3b. Programming Animated Statistical Graphics with R"
      - href: "Hands-On_Exercise/Hands-On_Exercise_04a.html"
        text: "4a. Visualising Distribution"
      - href: "Hands-On_Exercise/Hands-On_Exercise_04b.html"
        text: "4b. Visual Statistical Analysis"
      - href: "Hands-On_Exercise/Hands-On_Exercise_04c.html"
        text: "4c. Visualising Uncertainty"
      - href: "Hands-On_Exercise/Hands-On_Exercise_04d.html"
        text: "4d. Funnel Plots for Fair Comparisons"
        
        
    - text: "In-Class Exercise"
      menu:
      - href: https://public.tableau.com/views/In-Class_Ex01_17371865795720/Dashboard1?:language=en-GB&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
        text: "1. Sales and Profit Report"
      - href: https://public.tableau.com/views/In-Class_Ex02_17377898450610/Dashboard1?:language=en-GB&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
        text: "2. Interactive Sales and Profit Report"
      - href: https://public.tableau.com/views/In-Class_Ex03_17383926680820/InteractiveDashboard?:language=en-GB&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
        text: "3a. Sales vs Profit by State (Year Filter)"
      - href: https://public.tableau.com/views/In-Class_Ex03-1/SalesvsProfitbyMonthandYear?:language=en-GB&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
        text: "3b. Sales vs Profit by Month and Year"
      - href: https://public.tableau.com/views/In-Class_Ex03Story_17383932478800/Story1?:language=en-GB&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
        text: "3c. Sales vs Profit Story"
      - href: "In-Class_Exercise/In-Class_Ex04/In-Class_Exercise_4.html"
        text: "4. Boxplot"
    
    - text: "Take-Home Exercise"
      menu:
        - href: "Take-Home_Exercise/Take-Home_Exercise_1.html"
          text: "Take-Home Exercise 1"

format:
  html:
    theme:
      - journal
    css: styles.css
    toc: true

editor: visual

